name: finder
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  swipe_cards: ^1.0.0
  firebase_core: ^1.23.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cloud_firestore: ^3.4.7
  badges: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/