// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAheG28oZjwn3Df09AhasagKFrKfTFtyE',
    appId: '1:717195906789:web:bb60548c107e48283f4e0c',
    messagingSenderId: '717195906789',
    projectId: 'finder-7e2a7',
    authDomain: 'finder-7e2a7.firebaseapp.com',
    storageBucket: 'finder-7e2a7.appspot.com',
    measurementId: 'G-M4H9VQ8S60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8oOmJ4dVIWIg_10vQVfmwQTu5qbsMWY',
    appId: '1:717195906789:android:eedcbab18ad7b3383f4e0c',
    messagingSenderId: '717195906789',
    projectId: 'finder-7e2a7',
    storageBucket: 'finder-7e2a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQ1CxINZdlQl3XQLKQl6zcnTajzh8U-o',
    appId: '1:717195906789:ios:7e9e6ea05aaf645e3f4e0c',
    messagingSenderId: '717195906789',
    projectId: 'finder-7e2a7',
    storageBucket: 'finder-7e2a7.appspot.com',
    iosClientId: '717195906789-c42nlspql4ud4cnii97c75339bvoieuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQ1CxINZdlQl3XQLKQl6zcnTajzh8U-o',
    appId: '1:717195906789:ios:7e9e6ea05aaf645e3f4e0c',
    messagingSenderId: '717195906789',
    projectId: 'finder-7e2a7',
    storageBucket: 'finder-7e2a7.appspot.com',
    iosClientId: '717195906789-c42nlspql4ud4cnii97c75339bvoieuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finder',
  );
}
